name: iOS CI

on:
  push:
    branches: [ main ]

jobs:
  build:
    name: Build & Test
    runs-on: macos-14

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Select Xcode version
        run: sudo xcode-select -s /Applications/Xcode_15.0.1.app

      - name: Build app
        run: |
          xcodebuild \
            -project 3Kong1Cigarette.xcodeproj \
            -scheme 3Kong1Cigarette \
            -sdk iphonesimulator \
            -destination 'platform=iOS Simulator,name=iPhone 15' \
            clean build \
            CODE_SIGN_IDENTITY="" \
            CODE_SIGNING_REQUIRED=NO

      - name: Run Tests
        run: |
          xcodebuild \
            -project 3Kong1Cigarette.xcodeproj \
            -scheme 3Kong1Cigarette \
            -sdk iphonesimulator \
            -destination 'platform=iOS Simulator,name=iPhone 15' \
            test \
            CODE_SIGN_IDENTITY="" \
            CODE_SIGNING_REQUIRED=NO