
jobs:
  build:
    name: Build & Test
    runs-on: macos-13

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Select Xcode version
        run: sudo xcode-select -s /Applications/Xcode_15.0.app

      - name: Install xcpretty
        run: gem install xcpretty

      - name: Build and Run Tests with Output
        run: |
          set -o pipefail && \
          xcodebuild test \
            -workspace 3Kong1Cigarette.xcworkspace \
            -scheme 3Kong1Cigarette \
            -sdk iphonesimulator \
            -destination 'platform=iOS Simulator,name=iPhone 14' \
          | xcpretty
